# Generated by Django 4.2.1 on 2023-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eaddress', models.CharField(max_length=500)),
                ('eemail', models.EmailField(max_length=254)),
                ('ephno', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
