# Generated by Django 4.2.1 on 2023-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_ephno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
